services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /usr/local/bin/ollama:/usr/local/bin/ollama   
      - ~/.ollama:/root/.ollama 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
